// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.52.0_vite@5.4.20_terser@5.44.0__vue@3.5.21/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.52.0_vite@5.4.20_terser@5.44.0__vue@3.5.21/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/app/plugins/dev-server-logs").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.1_db0@0.3.2_ioredis@5.7.0_magicast@0.3.5_rollup@4.52.0__1a31b07f7713117b2c8c167473034568/node_modules/nuxt/dist/app/plugins/check-if-layout-used").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:revive-payload:server' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:chunk-reload' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
